// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zixikvltnpaaixngyssk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppeGlrdmx0bnBhYWl4bmd5c3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjMyODMsImV4cCI6MjA1OTgzOTI4M30.14mjSJDPE75rGnX6rUqMftc8BWbySjyEsQ0Hzv0sG_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);